# Generated by Django 4.2.7 on 2025-04-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='address',
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
